# Generated by Django 6.0.4 on 2026-05-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_setup_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
